basePath: /
definitions:
  handler.changeMovieStatusRequest:
    properties:
      mark:
        type: integer
      movie_id:
        type: integer
      review:
        type: string
      status:
        type: string
    type: object
  models.User:
    properties:
      avatar_url:
        type: string
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      registered_date:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
  models.UserSignInRequest:
    properties:
      email:
        default: marisasha228@bk.ru
        type: string
      password:
        default: "123"
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@ttl-checker.com
    name: API Support
  description: API для кино заметок
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: TTL Kinolog API
  version: "1.0"
paths:
  /api/movies/:
    get:
      consumes:
      - application/json
      description: Посмотреть все фильмы пользователя
      operationId: get-movies
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Посмотреть все фильмы
      tags:
      - movies
  /api/movies/{id}:
    get:
      consumes:
      - application/json
      description: Посмотреть фильм пользователя
      operationId: get-movie
      parameters:
      - description: Id movie
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Посмотреть фильм
      tags:
      - movies
  /api/movies/ai/search:
    get:
      consumes:
      - application/json
      description: Найти фильм
      operationId: search-movie
      parameters:
      - description: Название фильма
        in: query
        name: title
        type: string
      - description: Год выпуска
        in: query
        name: year
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Найти фильм
      tags:
      - movies
  /api/movies/delete/{id}:
    delete:
      consumes:
      - application/json
      description: Посмотреть фильм пользователя
      operationId: delete-movie
      parameters:
      - description: Id movie
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Удалить фильм
      tags:
      - movies
  /api/movies/status/change:
    put:
      consumes:
      - application/json
      description: Обновляет статус  кино
      operationId: update-status-movie
      parameters:
      - description: Id movie and status
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.changeMovieStatusRequest'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Обновить статус кино
      tags:
      - movies
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: Проверка прав пользователя
      operationId: sign-in
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UserSignInRequest'
      produces:
      - application/json
      responses: {}
      summary: Аутентификация пользователя
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: Создание нового пользователя
      operationId: sign-up
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses: {}
      summary: Регистрация пользователя
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    description: 'Введите: Bearer {token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
